// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://biffolmfhvghmbtfyxdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpZmZvbG1maHZnaG1idGZ5eGRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzMxODIsImV4cCI6MjA2NTE0OTE4Mn0.m1C28ChQD4mtz5rXlYfsP_LGYkxbr2pbRiZg8d0nckc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);